feat: use regex instead of `taplo` to extract channel in linter action

diff --git a/bevy_lint/action.yml b/bevy_lint/action.yml
--- a/bevy_lint/action.yml
+++ b/bevy_lint/action.yml
@@ -12,30 +12,38 @@ description: |
 runs:
   using: composite
   steps:
-    # Used to read `rust-toolchain.toml`.
-    - name: Install Taplo
-      uses: taiki-e/install-action@v2
-      with:
-        tool: taplo
-
-    # Read `rust-toolchain.toml` to find the exact nightly toolchain the linter needs.
-    - name: Extract toolchain
-      id: toolchain
+    # Use Regex to extract the `toolchain.channel` field in `rust-toolchain.toml`.
+    - name: Extract channel
+      id: channel
       shell: bash
       run: |
-        CHANNEL=$(taplo get --file-path="${RUST_TOOLCHAIN_PATH}" 'toolchain.channel')
-        COMPONENTS=$(taplo get --file-path="${RUST_TOOLCHAIN_PATH}" --separator=', ' 'toolchain.components')
+        # Read the contents of `rust-toolchain.toml`.
+        RUST_TOOLCHAIN=$(< "${RUST_TOOLCHAIN_PATH}")
 
-        echo "channel=${CHANNEL}" >> "${GITHUB_OUTPUT}"
-        echo "components=${COMPONENTS}" >> "${GITHUB_OUTPUT}"
+        # This Regex will capture the channel specified in `rust-toolchain.toml`.
+        REGEX='^channel = "(.+)"$'
+
+        if [[ "${RUST_TOOLCHAIN}" =~ "${REGEX}" ]]; then
+          # The `$BASH_REMATCH` variable stores the captured results. In this case,
+          # `${BASH_REMATCH[1]}` gives us the value of the first group, which is usually
+          # `nightly-YYYY-MM-DD`.
+          CHANNEL="${BASH_REMATCH[1]}"
+
+          echo "channel=${CHANNEL}" >> "${GITHUB_OUTPUT}"
+        else
+          echo "::error title=Could not extract channel::The Regex ${REGEX} did not match the contents of ${RUST_TOOLCHAIN_PATH}."
+          exit 1
+        fi
       env:
         RUST_TOOLCHAIN_PATH: ${{ github.action_path }}/../rust-toolchain.toml
 
     - name: Install Rust toolchain and components
       uses: dtolnay/rust-toolchain@master
       with:
-        toolchain: ${{ steps.toolchain.outputs.channel }}
-        components: ${{ steps.toolchain.outputs.components }}
+        toolchain: ${{ steps.channel.outputs.channel }}
+        # These components are hard-coded because they are unlikely to change. They should match
+        # `rust-toolchain.toml`.
+        components: rustc-dev, llvm-tools-preview
 
     - name: Install `bevy_lint`
       shell: bash
@@ -44,7 +52,7 @@ runs:
           --path "${BEVY_LINT_PATH}" \
           --locked
       env:
-        RUST_CHANNEL: ${{ steps.toolchain.outputs.channel }}
+        RUST_CHANNEL: ${{ steps.channel.outputs.channel }}
         # As the full contents of `TheBevyFlock/bevy_cli` is included alongside this action, we can
         # install the linter relative to the action path.
         BEVY_LINT_PATH: ${{ github.action_path }}
